### ISSUE TITLE
Getting a Type Error

### ISSUE THREAD

**Issue by aisha-yousuf** [trylinux/lift#22]
Hi, 

I tried running the code and it crashed with TypeError. Please see the command I used to run the code and the error I got below. How can I fix this error? To be fair, I still got the results, but code may need to be updated for future. 

Thanks!

> lift -f ~/2023sources.txt -p 80 -p 443 -o ~/2023outputfile.txt
2023-09-13 19:13:49.536442 | 212.121.105.53:80 | Samsung DVR Unknown type (Title)
2023-09-13 19:15:59.033896 | 157.231.59.90:80 | Hikvision-Based DVR (Server Only)
2023-09-13 19:17:32.147868 | 202.123.128.34:80 | Probable SonicWALL Network Security Appliance (Server name)
2023-09-13 19:24:12.004190 | 86.189.143.77:80 | Samsung DVR Unknown type (Title)
2023-09-13 19:37:41.777500 | 202.88.254.214:80 | Title is Battlefield 3 LAN | Battlelog | Log in and server is Apache/2.4.17 (Win32) OpenSSL/1.0.2d PHP/5.6.8 (NOID)
2023-09-13 19:41:51.254761 | 78.105.196.134:80 | Hikvision-Based DVR (Server Only)
2023-09-13 20:00:14.918905 | 43.251.87.186:80 | HikVision Device (Header and Script)
2023-09-13 20:07:36.673279 | 124.107.37.113:80 | MikroTik RouterOS version RouterOS v6.44.6(Login Page Title)
2023-09-13 20:08:22.750748 | 91.72.199.94:80 | Server: Apache with error HTTP Error 403: Forbidden (NOID) 
2023-09-13 20:19:11.825714 | 119.92.126.50:80 | has server nginx and no viewable title (NOID)
2023-09-13 20:38:01.227174 | 182.18.192.145:80 | has server lighttpd and no viewable title (NOID)
2023-09-13 20:38:04.792169 | 130.105.112.179:80 | has server lighttpd and no viewable title (NOID)
2023-09-13 20:41:25.371132 | 110.235.248.25:80 | IIS Windows Server Server (Page Title)
2023-09-13 20:45:49.730996 | 80.28.213.99:80 | Title is Inguralde - Iniciar Sesión and server is Apache/2.4.51 (Win64) OpenSSL/1.1.1l PHP/7.4.26 (NOID)
2023-09-13 21:03:33.261510 | 41.59.96.248:80 | Title is System Login and server is RapidLogic/1.1 (NOID)
2023-09-13 21:06:12.905642 | 46.99.132.133:80 | Dahua Product (DVR/NVR/HVR likely)
2023-09-13 21:29:13.577958 | 122.54.200.97:80 | has server nginx/1.18.0 and no viewable title (NOID)
Finishing scans...
Traceback (most recent call last):
  File "/home/liftCode/lift/venv/bin/lift", line 33, in <module>
    sys.exit(load_entry_point('lift', 'console_scripts', 'lift')())
  File "/home/liftCode/lift/lift/__main__.py", line 205, in main
    executor.shutdown(cancel_futures=True)
TypeError: shutdown() got an unexpected keyword argument 'cancel_futures'

**Comment by trylinux** [comment]
You have to be on python 3.9 or higher.
